Ticket/t21773 upgrade omniauth gem
venuenext/omniauth-openid-connect pull request #4
Opened 2022-09-02 13:07 UTC by ealvaro

2022-09-06 21:53 UTC, madeofstars0 requested changes

2022-09-06 21:53 UTC, madeofstars0 commented on omniauth-openid-connect.gemspec
> +  spec.authors       = ['John Bohn', 'Ilya Shcherbinin', 'Bryan Rehbein', 'Alvaro Escobar']
please update my name to Astra Rehbein and email to astra.rehbein@shift4.com

2022-09-07 12:50 UTC, ealvaro commented on omniauth-openid-connect.gemspec
> +  spec.authors       = ['John Bohn', 'Ilya Shcherbinin', 'Bryan Rehbein', 'Alvaro Escobar']
👍🏽

2022-09-07 22:31 UTC, madeofstars0 approved these changes

2022-09-08 13:05 UTC, merged